// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hroypeudumafiuzhcngs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhyb3lwZXVkdW1hZml1emhjbmdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg1MzA5NTUsImV4cCI6MjA3NDEwNjk1NX0.ZA4-QWjDz2FEPWf5oGtVsMKb0f5QUIf-kbHjDnVLQmk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});